version: "3.0"
services:
  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  engine:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"

    environment:
      FLOW_DSN: host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Europe/Moscow
      FLOW_HOSTNAME: localhost:8080
      FLOW_HTTPADDR: :8080
      FLOW_REDISHOST: redis
      FLOW_DEVELOPMENT: "true"

      FLOW_SHOWSQL: "false"