// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "saves new Nodes, Connections and EventCards",
                "operationId": "BatchSave",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/batch.SaveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/batch.SaveResponse"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deletes all Nodes, Connections and EventCards from the graph",
                "operationId": "BatchDelete",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/batch.DeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/batch.DeleteResponse"
                        }
                    }
                }
            }
        },
        "/call": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "executes callback",
                "operationId": "Call",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/engine.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/engine.Response"
                        }
                    }
                }
            }
        },
        "/connection": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "saves or updates Connection",
                "operationId": "SaveConnection",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.DBConnection"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graph.DBConnection"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deletes Connection",
                "operationId": "DeleteConnection",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.IDGraph"
                        }
                    }
                ]
            }
        },
        "/event-card": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "saves or updates EventCard",
                "operationId": "SaveEventCard",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.DBEventCard"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graph.DBEventCard"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deletes EventCard",
                "operationId": "DeleteEventCard",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.IDGraph"
                        }
                    }
                ]
            }
        },
        "/find-active": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "finds graphs that would activate for event",
                "operationId": "FindActive",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/search.FindActiveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/search.FindActiveResponse"
                        }
                    }
                }
            }
        },
        "/graph": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "gets graph with Nodes, Connections and EventCards",
                "operationId": "GetGraph",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "project id",
                        "name": "projectId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "graph id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graph.DBGraph"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "saves or updates graph. Nodes, Connections and EventCards are ignored",
                "operationId": "SaveGraph",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.DBGraph"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graph.DBGraph"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deletes graph and all related Nodes, Connections and EventCards",
                "operationId": "DeleteGraph",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.IDGraph"
                        }
                    }
                ]
            }
        },
        "/list-graphs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "lists graphs",
                "operationId": "ListGraph",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "description": "project ids",
                        "name": "projectId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.ListGraphResponse"
                        }
                    }
                }
            }
        },
        "/list-module": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "lists endpoints",
                "operationId": "ListEndpoint",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "project ids",
                        "name": "projectId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.Container"
                        }
                    }
                }
            }
        },
        "/module": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "saves Module",
                "operationId": "SaveEndpoint",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.DBEndpoint"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.DBEndpoint"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deletes Module",
                "operationId": "DeleteEndpoint",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.IDProject"
                        }
                    }
                ]
            }
        },
        "/node": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "saves or updates node",
                "operationId": "SaveNode",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.DBNode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/graph.DBNode"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deletes Node",
                "operationId": "DeleteNode",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/graph.IDGraph"
                        }
                    }
                ]
            }
        }
    },
    "definitions": {
        "batch.DeleteRequest": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "connections": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "projectId": {
                    "type": "integer"
                }
            }
        },
        "batch.DeleteResponse": {
            "type": "object"
        },
        "batch.SaveRequest": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBEventCard"
                    }
                },
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBConnection"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBNode"
                    }
                },
                "projectId": {
                    "type": "integer"
                }
            }
        },
        "batch.SaveResponse": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBEventCard"
                    }
                },
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBConnection"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBNode"
                    }
                },
                "projectId": {
                    "type": "integer"
                }
            }
        },
        "common.IDProject": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "projectId": {
                    "type": "integer"
                }
            }
        },
        "endpoint.Container": {
            "type": "object",
            "properties": {
                "map": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/endpoint.Endpoint"
                    }
                }
            }
        },
        "endpoint.DBEndpoint": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "module": {
                    "type": "string"
                },
                "projectId": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "endpoint.Endpoint": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "module": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "engine.Request": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "additionalProperties": true
                },
                "event": {
                    "$ref": "#/definitions/graph.DataEvent"
                },
                "raw": {
                    "type": "object"
                }
            }
        },
        "engine.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "noExecutions": {
                    "type": "boolean"
                },
                "response": {
                    "type": "object"
                },
                "scheduled": {
                    "type": "boolean"
                },
                "timeout": {
                    "type": "boolean"
                }
            }
        },
        "graph.DBConnection": {
            "type": "object",
            "properties": {
                "graphId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "localId": {
                    "description": "Placement",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "projectId": {
                    "type": "integer"
                },
                "sourceId": {
                    "type": "integer"
                },
                "sourcePort": {
                    "type": "string"
                },
                "targetId": {
                    "type": "integer"
                },
                "targetPort": {
                    "type": "string"
                },
                "ui": {
                    "type": "string"
                }
            }
        },
        "graph.DBEventCard": {
            "type": "object",
            "properties": {
                "contextId": {
                    "type": "string"
                },
                "contextType": {
                    "type": "string"
                },
                "graphId": {
                    "type": "integer"
                },
                "httpVote": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "initiatorId": {
                    "type": "string"
                },
                "initiatorType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                },
                "ownerType": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "projectId": {
                    "type": "integer"
                },
                "resourceId": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "slidePort": {
                    "type": "string"
                },
                "staticId": {
                    "type": "string"
                },
                "staticType": {
                    "type": "string"
                },
                "targetId": {
                    "description": "Placement",
                    "type": "integer"
                },
                "ui": {
                    "type": "string"
                }
            }
        },
        "graph.DBGraph": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBEventCard"
                    }
                },
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBConnection"
                    }
                },
                "counter": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBNode"
                    }
                },
                "projectId": {
                    "type": "integer"
                },
                "ui": {
                    "type": "string"
                }
            }
        },
        "graph.DBNode": {
            "type": "object",
            "properties": {
                "arguments": {
                    "type": "string"
                },
                "function": {
                    "type": "string"
                },
                "graphId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "localId": {
                    "description": "Placement",
                    "type": "integer"
                },
                "module": {
                    "description": "Invocation",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "projectId": {
                    "type": "integer"
                },
                "ui": {
                    "type": "string"
                }
            }
        },
        "graph.DataEvent": {
            "type": "object",
            "properties": {
                "contextId": {
                    "type": "string"
                },
                "contextType": {
                    "type": "string"
                },
                "initiatorId": {
                    "type": "string"
                },
                "initiatorType": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                },
                "ownerType": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "resourceId": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "staticId": {
                    "type": "string"
                },
                "staticType": {
                    "type": "string"
                }
            }
        },
        "graph.IDGraph": {
            "type": "object",
            "properties": {
                "graphId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "projectId": {
                    "type": "integer"
                }
            }
        },
        "search.ActiveGraph": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBEventCard"
                    }
                },
                "graph": {
                    "$ref": "#/definitions/graph.DBGraph"
                }
            }
        },
        "search.FindActiveRequest": {
            "type": "object",
            "properties": {
                "contextId": {
                    "type": "string"
                },
                "contextType": {
                    "type": "string"
                },
                "initiatorId": {
                    "type": "string"
                },
                "initiatorType": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                },
                "ownerType": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "resourceId": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "staticId": {
                    "type": "string"
                },
                "staticType": {
                    "type": "string"
                }
            }
        },
        "search.FindActiveResponse": {
            "type": "object",
            "properties": {
                "graphs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/search.ActiveGraph"
                    }
                }
            }
        },
        "storage.ListGraphResponse": {
            "type": "object",
            "properties": {
                "graphs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/graph.DBGraph"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
